import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

interface Expense {
  id: string;
  description: string;
  amount: number;
  category: string;
  date: string;
  notes: string | null;
}

interface Space {
  name: string;
  type: string;
  budget: number;
  spent: number;
  currency: string;
}

export function exportToCSV(expenses: Expense[], spaceName: string): void {
  const headers = ["Date", "Description", "Category", "Amount (₹)", "Notes"];
  
  const rows = expenses.map((expense) => [
    format(new Date(expense.date), "yyyy-MM-dd"),
    expense.description,
    expense.category,
    expense.amount.toFixed(2),
    expense.notes || "",
  ]);

  // Calculate total
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  rows.push(["", "", "Total", total.toFixed(2), ""]);

  const csvContent = [
    headers.join(","),
    ...rows.map((row) =>
      row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  
  link.setAttribute("href", url);
  link.setAttribute(
    "download",
    `${spaceName.replace(/[^a-z0-9]/gi, "_")}_expenses_${format(new Date(), "yyyy-MM-dd")}.csv`
  );
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToPDF(expenses: Expense[], space: Space): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(space.name, pageWidth / 2, 20, { align: "center" });

  // Subtitle
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Expense Report - ${format(new Date(), "MMMM dd, yyyy")}`, pageWidth / 2, 28, {
    align: "center",
  });

  // Summary section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, 42);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  
  const summaryData = [
    ["Space Type:", space.type],
    ["Total Budget:", `₹${space.budget.toLocaleString("en-IN")}`],
    ["Total Spent:", `₹${space.spent.toLocaleString("en-IN")}`],
    ["Remaining:", `₹${(space.budget - space.spent).toLocaleString("en-IN")}`],
    ["Budget Used:", `${space.budget > 0 ? ((space.spent / space.budget) * 100).toFixed(1) : 0}%`],
    ["Total Expenses:", `${expenses.length}`],
  ];

  let yPos = 48;
  summaryData.forEach(([label, value]) => {
    doc.text(label, 14, yPos);
    doc.text(value, 60, yPos);
    yPos += 6;
  });

  // Expenses table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Expense Details", 14, yPos + 10);

  const tableData = expenses.map((expense) => [
    format(new Date(expense.date), "dd/MM/yyyy"),
    expense.description.length > 30 
      ? expense.description.substring(0, 30) + "..." 
      : expense.description,
    expense.category,
    `₹${expense.amount.toLocaleString("en-IN")}`,
    expense.notes 
      ? (expense.notes.length > 20 ? expense.notes.substring(0, 20) + "..." : expense.notes)
      : "-",
  ]);

  // Add total row
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  tableData.push(["", "", "Total", `₹${total.toLocaleString("en-IN")}`, ""]);

  autoTable(doc, {
    startY: yPos + 15,
    head: [["Date", "Description", "Category", "Amount", "Notes"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: 255,
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 50 },
      2: { cellWidth: 30 },
      3: { cellWidth: 30, halign: "right" },
      4: { cellWidth: 40 },
    },
    foot: [],
    didParseCell: (data) => {
      // Style the total row
      if (data.row.index === tableData.length - 1) {
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by Tracura - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // Save the PDF
  doc.save(
    `${space.name.replace(/[^a-z0-9]/gi, "_")}_expenses_${format(new Date(), "yyyy-MM-dd")}.pdf`
  );
}
